-- Generated by scripts/sync-ml-products.py from the supplied spreadsheet.
-- Only high-confidence, one-sale-unit matches are included.
SET NAMES utf8mb4;
START TRANSACTION;
UPDATE ws_product SET price = 19.9000, quantity = 0, status = 0, date_modified = NOW(), length = 3.00000000, width = 16.00000000, height = 19.00000000, weight = 0.28000000 WHERE product_id = 1;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 1/4 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 1/4 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 1 AND language_id = 2;
UPDATE ws_product SET price = 26.9000, quantity = 41, status = 1, date_modified = NOW(), length = 3.00000000, width = 17.00000000, height = 22.00000000, weight = 0.17000000 WHERE product_id = 3;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 5/16 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 5/16 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 3 AND language_id = 2;
UPDATE ws_product SET price = 29.9000, quantity = 41, status = 1, date_modified = NOW(), length = 3.00000000, width = 17.00000000, height = 22.00000000, weight = 0.14000000 WHERE product_id = 5;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 3/8 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 3/8 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 5 AND language_id = 2;
UPDATE ws_product SET price = 47.0400, quantity = 47, status = 1, date_modified = NOW(), length = 5.00000000, width = 17.00000000, height = 23.00000000, weight = 0.22000000 WHERE product_id = 7;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 1/2 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 1/2 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 7 AND language_id = 2;
UPDATE ws_product SET price = 35.9000, quantity = 10, status = 1, date_modified = NOW(), length = 3.00000000, width = 14.00000000, height = 18.00000000, weight = 0.12000000 WHERE product_id = 11;
UPDATE ws_product_description SET description = '<p>Bits Quadrado 10% Cobalto 1/4 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 1/4 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 11 AND language_id = 2;
UPDATE ws_product SET price = 46.9000, quantity = 10, status = 1, date_modified = NOW(), length = 5.00000000, width = 20.00000000, height = 26.00000000, weight = 0.19000000 WHERE product_id = 13;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 5/16 x 4 10%Co</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 5/16 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 13 AND language_id = 2;
UPDATE ws_product SET price = 69.9000, quantity = 19, status = 1, date_modified = NOW() WHERE product_id = 15;
UPDATE ws_product_description SET description = '<p>Bits Quadrado 10% Cobalto 3/8 x 4</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 3/8 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 15 AND language_id = 2;
UPDATE ws_product SET price = 129.9000, quantity = 50, status = 1, date_modified = NOW(), length = 7.00000000, width = 13.00000000, height = 27.00000000, weight = 0.47000000 WHERE product_id = 17;
UPDATE ws_product_description SET description = '<p>Bits Quadrado HSS 1/2 x 4 10%Co</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bits Quadrado<br>Medida: 1/2 x 4<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 17 AND language_id = 2;
UPDATE ws_product SET price = 33.6300, quantity = 46, status = 1, date_modified = NOW(), length = 4.00000000, width = 17.00000000, height = 26.00000000, weight = 0.38000000 WHERE product_id = 21;
UPDATE ws_product_description SET description = '<p>Bedames HSS 1/2 x 1/8 x 6</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedames HSS<br>Medida: 1/2 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 21 AND language_id = 2;
UPDATE ws_product SET price = 53.9900, quantity = 0, status = 0, date_modified = NOW(), length = 3.00000000, width = 17.00000000, height = 23.00000000, weight = 0.28000000 WHERE product_id = 22;
UPDATE ws_product_description SET description = '<p>Bedames HSS 5/8 x 1/8 x 6</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedames HSS<br>Medida: 5/8 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 22 AND language_id = 2;
UPDATE ws_product SET price = 59.4000, quantity = 50, status = 0, date_modified = NOW() WHERE product_id = 23;
UPDATE ws_product_description SET description = '<p>Bedames HSS 3/4 x 1/8 x 6</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedames HSS<br>Medida: 3/4 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 23 AND language_id = 2;
UPDATE ws_product SET price = 77.6500, quantity = 49, status = 1, date_modified = NOW(), length = 7.00000000, width = 12.00000000, height = 17.00000000, weight = 0.36000000 WHERE product_id = 24;
UPDATE ws_product_description SET description = '<p>Bedames 1/2 x 1/8 x 6 c/ 10% Co</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedame 10% Co<br>Medida: 1/2 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 24 AND language_id = 2;
UPDATE ws_product SET price = 94.9000, quantity = 50, status = 1, date_modified = NOW(), length = 5.00000000, width = 14.00000000, height = 25.00000000, weight = 0.38000000 WHERE product_id = 25;
UPDATE ws_product_description SET description = '<p>Bedames 5/8 x 1/8 x 6 c/ 10% Co</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedame 10% Co<br>Medida: 5/8 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 25 AND language_id = 2;
UPDATE ws_product SET price = 89.0600, quantity = 40, status = 1, date_modified = NOW(), length = 3.00000000, width = 11.00000000, height = 19.00000000, weight = 0.53000000 WHERE product_id = 26;
UPDATE ws_product_description SET description = '<p>Bedames 3/4 x 1/8 x 6 c/ 10% Co</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bedame 10% Co<br>Medida: 3/4 x 1/8 x 6<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com 10% Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 2 meses</p>' WHERE product_id = 26 AND language_id = 2;
UPDATE ws_product SET price = 159.6000, quantity = 0, status = 0, date_modified = NOW(), length = 5.00000000, width = 10.00000000, height = 18.00000000, weight = 0.36000000 WHERE product_id = 32;
UPDATE ws_product_description SET description = '<p>Porta Bits Reto 1/2</p>
<p>Características:<br>Marca: Hispânia<br>Produto: Porta Bits Reto<br>Medida: 1/2<br>Quantidade: 1 unidade<br>Descrição: Fabricado com aço importado com Cobalto, proporcionando maior resistência a altas temperaturas e ao desgaste sem perder o corte;<br>Norma: DIN4964;</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 32 AND language_id = 2;
UPDATE ws_product SET price = 959.9000, quantity = 0, status = 0, date_modified = NOW(), length = 11.00000000, width = 21.00000000, height = 37.00000000, weight = 1.96000000 WHERE product_id = 181;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril Cone Morse 4</p>
<p>Características do kit:</p>
<p>Mandril Cone Morse 4 <br>Quantidade: 1 unidade<br>Tipo de Cone: Cone Morse cônico (CM4) com rabo reto.<br>Norma Aplicável: DIN 228-1, que especifica cones Morse com rabo reto.<br>Diâmetro maior: 31,267 mm. <br>Rosca traseira: Pode variar, mas um exemplo comum é M16x2. <br>Comprimento: Também pode variar, mas um exemplo comum é 71,7 mm. <br>Material: Geralmente construído em aço ferramenta 8620, com cementação para maior resistência e durabilidade.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 181 AND language_id = 2;
UPDATE ws_product SET price = 930.0500, quantity = 1, status = 1, date_modified = NOW(), length = 13.00000000, width = 29.00000000, height = 40.00000000, weight = 1.96000000 WHERE product_id = 182;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril Cone Morse 5</p>
<p>Características do kit:</p>
<p>Mandril Cone Morse 5 <br>Quantidade: 1 unidade<br>Tipo de Cone: Cone Morse cônico (CM5) com rabo reto.<br>Norma Aplicável: DIN 228-1, que especifica cones Morse com rabo reto.<br>Diâmetro maior: 44,7 mm. <br>Diâmetro Menor: 38,1 mm.<br>Rosca traseira: Pode variar, mas um exemplo comum é M20 x 2,5. <br>Comprimento: O comprimento do cone, medido a partir da face do encaixe até o final do corpo, pode variar ligeiramente dependendo do fabricante, mas um valor comum é 82 mm.<br>Material: Geralmente construído em aço ferramenta 8620, com cementação para maior resistência e durabilidade.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 182 AND language_id = 2;
UPDATE ws_product SET price = 1035.9000, quantity = 0, status = 0, date_modified = NOW(), length = 14.00000000, width = 30.00000000, height = 39.00000000, weight = 4.93000000 WHERE product_id = 183;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril ISO 30</p>
<p>Características do kit:</p>
<p>Mandril ISO 30<br>Quantidade: 1 unidade<br>Tipo de Cone: Cone ISO 30, com encaixe cônico padrão para máquinas CNC e centros de usinagem.<br>Norma Aplicável: Conforme a norma ISO 7388-1, que define os requisitos para cones de fixação tipo ISO.<br>Diâmetro Maior: Aproximadamente 31,75 mm (na base do cone).<br>Diâmetro Menor: Cerca de 17,78 mm (na extremidade do cone).<br>Rosca Traseira: Normalmente M12 x 1,75, utilizada para fixação por tração em máquinas CNC.<br>Comprimento Total: O comprimento padrão do cone ISO 30 é de aproximadamente 68 mm, podendo variar ligeiramente conforme o fabricante.<br>Material: Fabricado geralmente em aço-liga de alta resistência, com tratamento térmico (como têmpera e revenimento) para garantir durabilidade, rigidez e resistência ao desgaste.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 183 AND language_id = 2;
UPDATE ws_product SET price = 1021.8200, quantity = 2, status = 1, date_modified = NOW(), length = 10.00000000, width = 26.00000000, height = 39.00000000, weight = 3.48000000 WHERE product_id = 184;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril ISO 40</p>
<p>Características do kit:</p>
<p>Mandril ISO 40<br>Quantidade: 1 unidade<br>Tipo de Cone: Cone ISO 40, amplamente utilizado em centros de usinagem e máquinas CNC de médio porte.<br>Norma Aplicável: Atende à norma ISO 7388-1, que padroniza os cones de fixação tipo ISO para ferramentas de corte.<br>Diâmetro Maior: Aproximadamente 44,45 mm na base do cone.<br>Diâmetro Menor: Cerca de 19,05 mm na extremidade do cone.<br>Rosca Traseira: Comumente M16 x 2, utilizada para sistemas de fixação por tração.<br>Comprimento Total: O comprimento padrão do cone ISO 40 é de aproximadamente 100 mm, podendo variar levemente conforme o fabricante.<br>Material: Produzido geralmente em aço-liga de alta resistência, com tratamentos térmicos como cementação ou têmpera para garantir maior durabilidade, rigidez e resistência ao desgaste.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 184 AND language_id = 2;
UPDATE ws_product SET price = 1017.4500, quantity = 0, status = 0, date_modified = NOW(), length = 21.00000000, width = 32.00000000, height = 41.00000000, weight = 8.05000000 WHERE product_id = 185;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril ISO 50</p>
<p>Características do kit:</p>
<p>Mandril ISO 50<br>Quantidade: 1 unidade<br>ipo de Cone: Cone ISO 50, utilizado em máquinas CNC de grande porte e aplicações industriais pesadas.<br>Norma Aplicável: Conforme a norma ISO 7388-1, que padroniza os cones de fixação tipo ISO para ferramentas de corte.<br>Diâmetro Maior: Aproximadamente 69,85 mm na base do cone.<br>Diâmetro Menor: Cerca de 31,75 mm na extremidade do cone.<br>Rosca Traseira: Normalmente M24 x 3, adequada para sistemas de fixação por tração robustos.<br>Comprimento Total: O comprimento padrão do cone ISO 50 é de aproximadamente 135 mm, podendo variar conforme o fabricante.<br>Material: Fabricado geralmente em aço-liga de alta resistência, com tratamentos térmicos como cementação ou têmpera para garantir excelente durabilidade, rigidez e resistência ao desgaste, mesmo sob cargas elevadas.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 185 AND language_id = 2;
UPDATE ws_product SET price = 990.0000, quantity = 1, status = 1, date_modified = NOW() WHERE product_id = 186;
UPDATE ws_product_description SET description = '<p>Jogo de Pinças ER40 18 Peças + Chave + Mandril BT40</p>
<p>Características do kit:</p>
<p>Mandril BT40<br>Quantidade: 1 unidade<br>Tipo de Cone: Cone BT 40, com dupla face de contato (flange e cone), ideal para centros de usinagem CNC que exigem alta rigidez e precisão.<br>Norma Aplicável: Atende à norma MAS 403-BT, que padroniza os cones tipo BT utilizados em máquinas CNC.<br>Diâmetro Maior: Aproximadamente 44,45 mm na base do cone.<br>Diâmetro Menor: Cerca de 19,05 mm na extremidade do cone.<br>Rosca Traseira: Comumente M16 x 2, utilizada para sistemas de fixação por tração com puxadores padrão BT.<br>Comprimento Total: O comprimento padrão do cone BT 40 é de aproximadamente 100 mm, podendo variar levemente conforme o fabricante.<br>Material: Fabricado geralmente em aço-liga de alta resistência, com tratamentos térmicos como têmpera e revenimento para garantir excelente durabilidade, rigidez e resistência ao desgaste, mesmo em operações de alta velocidade.</p>
<p>Chave de Garra<br>Quantidade: 1 unidade<br>Tipo: Chave específica para pinças ER40.<br>Material: Aço resistido para maior durabilidade e resistência ao desgaste.</p>
<p>Jogo de Pinça ER-40<br>Quantidade: 18 Pinças no Jogo<br>Material: Aço especial tratado termicamente, garantindo maior durabilidade e resistência ao desgaste.<br>Diâmetro Nominal de Fixação: 4 mm a 20 mm, mais uma pinça adicional de 25 mm.<br>Flexibilidade: Cada pinça ER40 pode acomodar diâmetros de até 1 mm abaixo do diâmetro nominal.<br>Diâmetro externo: 40 mm.<br>Comprimento total: 46 mm.<br>Precisão: Concentricidade de 0,01 mm TIR (Total Indicator Reading), conforme DIN ISO 15488.</p>
<p>Indicações:<br>- Indicada para fresamento, mandrilamento, furação e rosqueamento em ambientes de produção que desbloqueiam alta precisão</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra de</p>
<p>Garantia de fábrica: 2 meses</p>' WHERE product_id = 186 AND language_id = 2;
UPDATE ws_product SET price = 166.9000, quantity = 1, status = 0, date_modified = NOW() WHERE product_id = 195;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Standard CM2</p>
<p>Características:<br>Marca: Gold<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens com cargas axiais leves.</p>
<p>Composição:<br>- Mancal composto por 2 rolamentos radiais de esferas.<br>- Possui 1 rolamento de esferas blindado para proteger a ponta contra a entrada de cavacos e outras impurezas.<br>- Diâmetro do corpo externo reduzido, facilitando as usinagens de peças de pequeno tamanho.<br>- Eixo giratório temperado, revenido (60+/- 2HCR) e retificado<br>- Ponta rotativa de baixo custo</p>
<p>Características:<br>- Cone Morse: CM2<br>- Tamanho da Ponta: 28,6mm<br>- Diâmetro da ponta: 25mm<br>- Diâmetro do corpo: 45mm<br>- Comprimento: 129,60mm<br>- Peso Máximo da Peça: 0,475 Kg<br>- Tipo: Carga Leve e Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 195 AND language_id = 2;
UPDATE ws_product SET price = 291.0600, quantity = 7, status = 1, date_modified = NOW(), length = 7.00000000, width = 14.00000000, height = 22.00000000, weight = 0.98000000 WHERE product_id = 196;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Standard CM3</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens com cargas axiais leves.</p>
<p>Composição:<br>- Mancal composto por 2 rolamentos radiais de esferas.<br>- Possui 1 rolamento de esferas blindado para proteger a ponta contra a entrada de cavacos e outras impurezas.<br>- Diâmetro do corpo externo reduzido, facilitando as usinagens de peças de pequeno tamanho.<br>- Eixo giratório temperado, revenido (60+/- 2HCR) e retificado<br>- Ponta rotativa de baixo custo</p>
<p>Características:<br>- Cone Morse: CM3<br>- Tamanho da Ponta: 32mm<br>- Diâmetro da ponta: 28mm<br>- Diâmetro do corpo: 58mm<br>- Comprimento: 160.2mm<br>- Peso Máximo da Peça: 0,812 Kg<br>- Tipo: Carga Leve e Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 196 AND language_id = 2;
UPDATE ws_product SET price = 189.0000, quantity = 0, status = 0, date_modified = NOW(), length = 11.00000000, width = 17.00000000, height = 25.00000000, weight = 1.53000000 WHERE product_id = 197;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Standard CM4</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens com cargas axiais leves.</p>
<p>Composição:<br>- Mancal composto por 2 rolamentos radiais de esferas.<br>- Possui 1 rolamento de esferas blindado para proteger a ponta contra a entrada de cavacos e outras impurezas.<br>- Diâmetro do corpo externo reduzido, facilitando as usinagens de peças de pequeno tamanho.<br>- Eixo giratório temperado, revenido (60+/- 2HCR) e retificado<br>- Ponta rotativa de baixo custo</p>
<p>Características:<br>- Cone Morse: CM4<br>- Tamanho da Ponta: 34.5mm<br>- Diâmetro da ponta: 32mm<br>- Diâmetro do corpo: 60mm<br>- Comprimento: 191.7mm<br>- Peso Máximo da Peça: 1,300 Kg<br>- Tipo: Carga Leve e Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 197 AND language_id = 2;
UPDATE ws_product SET price = 289.9000, quantity = 4, status = 1, date_modified = NOW(), length = 9.00000000, width = 14.00000000, height = 19.00000000, weight = 1.08000000 WHERE product_id = 198;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Super CM3</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens onde exige-se alta rotação.</p>
<p>Composição:<br>- Montagem espaçada dos rolamentos no eixo giratório permite ótima rigidez e perfeita concentricidade de rotação da ponta; <br>- Corpo externo usinado, temperado e revenido (40 + 2HCR) e retificado); <br>- Eixo giratório temperado, revenido (60 + 2HCR) e retificado.</p>
<p>Características:<br>- Cone Morse: CM3<br>- Tamanho da Ponta: 38mm<br>- Diâmetro da ponta: 28mm<br>- Diâmetro do corpo: 59mm<br>- Comprimento: 170mm<br>- Peso Máximo da Peça: 0,966 Kg<br>- Tipo: Carga Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 198 AND language_id = 2;
UPDATE ws_product SET price = 285.9000, quantity = 4, status = 1, date_modified = NOW(), length = 11.00000000, width = 17.00000000, height = 24.00000000, weight = 1.71000000 WHERE product_id = 199;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Super CM4</p>
<p>Características:<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens onde exige-se alta rotação.</p>
<p>Composição:<br>- Montagem espaçada dos rolamentos no eixo giratório permite ótima rigidez e perfeita concentricidade de rotação da ponta; <br>- Corpo externo usinado, temperado e revenido (40 + 2HCR) e retificado); <br>- Eixo giratório temperado, revenido (60 + 2HCR) e retificado.</p>
<p>Características:<br>- Cone Morse: CM4<br>- Tamanho da Ponta: 45mm<br>- Diâmetro da ponta: 31mm<br>- Diâmetro do corpo: 64mm<br>- Comprimento: 198mm<br>- Peso Máximo da Peça: 1,600 Kg<br>- Tipo: Carga Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 199 AND language_id = 2;
UPDATE ws_product SET price = 735.5000, quantity = 1, status = 1, date_modified = NOW(), length = 14.00000000, width = 16.00000000, height = 31.00000000, weight = 3.08000000 WHERE product_id = 200;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Super CM5</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Indicadas para serviços gerais de tornearia - utilização em tornos e CNC<br>- Usinagens de cargas radiais, leves e médias, de média precisão.<br>- Usinagens onde exige-se alta rotação.</p>
<p>Composição:<br>- Montagem espaçada dos rolamentos no eixo giratório permite ótima rigidez e perfeita concentricidade de rotação da ponta; <br>- Corpo externo usinado, temperado e revenido (40 + 2HCR) e retificado); <br>- Eixo giratório temperado, revenido (60 + 2HCR) e retificado.</p>
<p>Características:<br>- Cone Morse: CM5<br>- Tamanho da Ponta: 52mm<br>- Diâmetro da ponta: 44mm<br>- Diâmetro do corpo: 78mm<br>- Comprimento: 245mm<br>- Peso Máximo da Peça: 3,415 Kg<br>- Tipo: Carga Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>
<p>Garantia do vendedor: 3 meses</p>' WHERE product_id = 200 AND language_id = 2;
UPDATE ws_product SET price = 311.8500, quantity = 1, status = 1, date_modified = NOW() WHERE product_id = 201;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Copiadora CM3</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Para usinagens de média precisão;<br>- Trabalhos de cargas radiais e axiais médias e pesadas;<br>- Ideal para usinagem onde exige-se alta rotação.</p>
<p>Composição:<br>- Mancal composto por 2 rolamentos radiais de esferas.<br>- Possui 1 rolamento de esferas blindado para proteger a ponta contra a entrada de cavacos e outras impurezas.<br>- Eixo giratório temperado, revenido (60+/- 2HCR) e retificado<br>- Ponta rotativa de baixo custo</p>
<p>Características:<br>- Cone Morse: CM3<br>- Tamanho da Ponta: 43mm<br>- Diâmetro da ponta: 21mm<br>- Diâmetro do corpo: 51 mm<br>- Peso Máximo da Peça: 0,865 Kg<br>- Tipo: Carga Leve e Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação&quot;</p>' WHERE product_id = 201 AND language_id = 2;
UPDATE ws_product SET price = 335.0000, quantity = 4, status = 1, date_modified = NOW(), length = 8.00000000, width = 15.00000000, height = 22.00000000, weight = 1.45000000 WHERE product_id = 202;
UPDATE ws_product_description SET description = '<p>Ponta Rotativa Copiadora CM4</p>
<p>Características:<br>Marca: Winner Steel<br>Quantidade: 1 unidade</p>
<p>Indicações:<br>- Para usinagens de média precisão;<br>- Trabalhos de cargas radiais e axiais médias e pesadas;<br>- Ideal para usinagem onde exige-se alta rotação.</p>
<p>Composição:<br>- Mancal composto por 2 rolamentos radiais de esferas.<br>- Possui 1 rolamento de esferas blindado para proteger a ponta contra a entrada de cavacos e outras impurezas.<br>- Eixo giratório temperado, revenido (60+/- 2HCR) e retificado<br>- Ponta rotativa de baixo custo</p>
<p>Características:<br>- Cone Morse: CM4<br>- Tamanho da Ponta: 45mm<br>- Diâmetro da ponta: 30mm<br>- Diâmetro do corpo: 67mm<br>- Peso Máximo da Peça: 1,319 Kg<br>- Tipo: Carga Leve e Média</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 202 AND language_id = 2;
UPDATE ws_product SET price = 36.9000, quantity = 9, status = 1, date_modified = NOW(), length = 4.00000000, width = 11.00000000, height = 17.00000000, weight = 0.12000000 WHERE product_id = 211;
UPDATE ws_product_description SET description = '<p>1 Bucha de Redução Cone Morse 2 x 1 P/ Torno</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bucha de Redução<br>Medida: 2 x 1<br>Quantidade: 1 unidade<br>Descrição: Inteiramente retificada.<br>Acessório utilizado na adaptação de ferramentas com fixação em cone-morse menor que o existente na árvore da máquina.</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 211 AND language_id = 2;
UPDATE ws_product SET price = 54.9900, quantity = 1, status = 1, date_modified = NOW(), length = 7.00000000, width = 12.00000000, height = 17.00000000, weight = 0.21000000 WHERE product_id = 212;
UPDATE ws_product_description SET description = '<p>1 Bucha de Redução Cone Morse 3 x 2 P/ Torno</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bucha de Redução<br>Medida: 3 x 2<br>Quantidade: 1 unidade<br>Descrição: Inteiramente retificada.<br>Acessório utilizado na adaptação de ferramentas com fixação em cone-morse menor que o existente na árvore da máquina.</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 212 AND language_id = 2;
UPDATE ws_product SET price = 72.9900, quantity = 2, status = 1, date_modified = NOW(), length = 4.00000000, width = 10.00000000, height = 18.00000000, weight = 0.46000000 WHERE product_id = 213;
UPDATE ws_product_description SET description = '<p>1 Bucha de Redução Cone Morse 4 x 3 P/ Torno</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bucha de Redução<br>Medida: 4 x 3<br>Quantidade: 1 unidade<br>Descrição: Inteiramente retificada.<br>Acessório utilizado na adaptação de ferramentas com fixação em cone-morse menor que o existente na árvore da máquina.</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 213 AND language_id = 2;
UPDATE ws_product SET price = 119.9900, quantity = 8, status = 1, date_modified = NOW(), length = 8.00000000, width = 15.00000000, height = 22.00000000, weight = 1.01000000 WHERE product_id = 214;
UPDATE ws_product_description SET description = '<p>1 Bucha de Redução Cone Morse 5 x 4 P/ Torno</p>
<p>Características:<br>Marca: Winner Steel<br>Produto: Bucha de Redução<br>Medida: 5 x 4<br>Quantidade: 1 unidade<br>Descrição: Inteiramente retificada.<br>Acessório utilizado na adaptação de ferramentas com fixação em cone-morse menor que o existente na árvore da máquina.</p>
<p>-------------------------------------------</p>
<p>- Fotos reais dos produtos</p>
<p>- Atendimento Com Qualidade - Vários Canais de Atendimento</p>
<p>- Devolução Gratuita - Isso mesmo, Sem custos!</p>
<p>- Frete Seguro Para Todo Brasil</p>
<p>- Frete Grátis para mais de uma peça adquirida</p>
<p>- Produtos Com Garantia - Proteção para você e sua compra</p>
<p>- Produtos a pronta entrega</p>
<p>- Garantimos a devolução por arrependimento em até 7 dias após o recebimento e garantia de 90 dias contra defeitos de fabricação</p>' WHERE product_id = 214 AND language_id = 2;
COMMIT;
